name: Deploy Spring Boot Backend to KillerKoda

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Copy JAR to KillerKoda
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.NGROK_HOST }}
          port: ${{ secrets.NGROK_PORT }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "target/property-booking-app-0.0.1-SNAPSHOT.jar"
          target: "/home/${{ secrets.EC2_USER }}/app/"

      - name: Restart Spring Boot service
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.NGROK_HOST }}
          port: ${{ secrets.NGROK_PORT }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo systemctl stop property-app || true
            sudo mv /home/${{ secrets.EC2_USER }}/app/target/property-booking-app-0.0.1-SNAPSHOT.jar /opt/property-app.jar
            sudo bash -c 'cat > /etc/systemd/system/property-app.service <<EOF
            [Unit]
            Description=Spring Boot Property App
            After=network.target

            [Service]
            User=indhuarunvel1988
            ExecStart=/usr/bin/java -Djava.net.preferIPv4Stack=true -jar /opt/property-app.jar
            SuccessExitStatus=143
            Restart=always
            RestartSec=10

            [Install]
            WantedBy=multi-user.target
            EOF'
            sudo systemctl daemon-reload
            sudo systemctl enable property-app
            sudo systemctl start property-app
